name: unit_testing
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  injectable: ^2.1.0
  json_annotation: ^4.7.0
  shared_preferences: ^2.0.15
  connectivity_checker: ^1.1.0
  fast_flutter_driver: ^3.0.0+1
  dio: ^4.0.6


dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test: ^1.16.0
  mockito: 
  flutter_lints: ^2.0.0
  build_runner:
  bloc_test: 
  json_serializable: ^6.5.4
  injectable_generator: ^2.1.3

flutter:

  uses-material-design: true

